#gui:
  ## stuff relating to the UI
  #scrollHeight: 2 # how many lines you scroll by
  #scrollPastBottom: true # enable scrolling past the bottom
  #sidePanelWidth: 0.3333 # number from 0 to 1
  #expandFocusedSidePanel: false
  #mainPanelSplitMode: 'flexible' # one of 'horizontal' | 'flexible' | 'vertical'
  #theme:
    #lightTheme: false # For terminals with a light background
    #activeBorderColor:
      #- white
      #- bold
    #inactiveBorderColor:
      #- green
    #optionsTextColor:
      #- blue
    #selectedLineBgColor:
      #- default
    #selectedRangeBgColor:
      #- blue
  #commitLength:
    #show: true
  #mouseEvents: true
  #skipUnstageLineWarning: false
  #skipStashWarning: true
  #showFileTree: false # for rendering changes files in a tree format
  #showListFooter: true # for seeing the '5 of 20' message in list panels
  #showRandomTip: true
  #showCommandLog: true
  #commandLogSize: 8
#git:
  #paging:
    #colorArg: always
    #useConfig: false
  #merging:
    ## only applicable to unix users
    #manualCommit: false
    ## extra args passed to `git merge`, e.g. --no-ff
    #args: ''
  #pull:
    #mode: 'auto' # one of 'auto' | 'merge' | 'rebase' | 'ff-only', auto reads from git configuration
  #skipHookPrefix: WIP
  #autoFetch: true
  #branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --'
  #allBranchesLogCmd: 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium'
  #overrideGpg: false # prevents lazygit from spawning a separate process when using GPG
  #disableForcePushing: false
#os:
  #editCommand: '' # see 'Configuring File Editing' section
  #openCommand: ''
#refresher:
  #refreshInterval: 10 # file/submodule refresh interval in seconds
  #fetchInterval: 60 # re-fetch interval in seconds
#update:
  #method: prompt # can be: prompt | background | never
  #days: 14 # how often an update is checked for
#reporting: 'undetermined' # one of: 'on' | 'off' | 'undetermined'
#confirmOnQuit: false
## determines whether hitting 'esc' will quit the application when there is nothing to cancel/close
#quitOnTopLevelReturn: false
#disableStartupPopups: false
#notARepository: 'prompt' # one of: 'prompt' | 'create' | 'skip'

#keybinding:
  #universal:
    #prevItem-alt: 'u'
    #nextItem-alt: 'e'
    #prevBlock-alt: 'n'
    #nextBlock-alt: 'i'
    #nextMatch: '='
    #prevMatch: '-'
    #new: 'k'
    #edit: 'o'
    #openFile: 'O'
    #scrollUpMain-alt1: 'U'
    #scrollDownMain-alt1: 'E'
    #scrollUpMain-alt2: '<c-u>'
    #scrollDownMain-alt2: '<c-e>'
    #undo: 'l'
    #redo: '<c-r>'
    #diffingMenu: 'M'
    #filteringMenu: '<c-f>'
  #files:
    #ignoreFile: 'I'
  #commits:
    #moveDownCommit: '<c-e>'
    #moveUpCommit: '<c-u>'
  #branches:
    #viewGitFlowOptions: 'I'

confirmonquit: false
git:
  autofetch: true
  merging:
    manualcommit: false
  skiphookprefix: WIP
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --theme="OneHalfDark"
gui:
  commitlength:
    show: true
  mouseevents: false
  scrollheight: 2
  scrollpastbottom: true
  theme:
    lightTheme: false
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - blue
reporting: "off"
splashupdatesindex: 0
startuppopupversion: 1
keybinding:
  universal:
    quit-alt1: '<esc>'
    prevItem-alt: 'u'
    nextItem-alt: 'e'
    prevBlock-alt: 'n'
    nextBlock-alt: 'i'
    nextMatch: '='
    prevMatch: '-'
    new: 'k'
    edit: 'o'
    openFile: 'O'
    scrollUpMain-alt1: 'U'
    scrollDownMain-alt1: 'E'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-e>'
    undo: 'l'
    redo: '<c-r>'
    diffingMenu: 'M'
    filteringMenu: '<c-f>'
  files:
    ignoreFile: 'I'
  commits:
    moveDownCommit: '<c-e>'
    moveUpCommit: '<c-u>'
  branches:
    viewGitFlowOptions: 'I'
    setUpstream: 'U'
