alias vim="nvim"
alias c="clear"
alias ra="ranger"
#alias sproxy1="export http_proxy=http://127.0.0.1:7890"
#alias sproxy2="export https_proxy=http://127.0.0.1:7890"
alias proxy="bash ~/scripts/proxy.sh"
alias cl="bash ~/scripts/clash.sh"
alias s="cd"
alias new="mkdir"
alias ls="exa"
alias lsa="exa -abghHliS"
alias gogo="cd;cd go/src"
alias sshy="ssh Yongteng@172.16.2.17"
alias sshr="ssh root@121.40.151.71"


